### ISSUE TITLE
HyperRectangle getting confused

### ISSUE THREAD

**Issue by antoine-levitt** [maltezfaria/ImplicitIntegration.jl#5]
I get this error:
```
┌ Warning: Terminal case of recursion reached on ImplicitIntegration.HyperRectangle{2, Float64}([0.6666666716337204, 0.3333333432674408], [0.666666679084301, 0.3333333507180214]), resorting to low-order method.
└ @ ImplicitIntegration ~/Dropbox/recherche/2024-09-implicit integration/ImplicitIntegration.jl/src/integration.jl:171
```
which looks like it's getting confused and taking a hc lower than a lc. I think it's a bug in implicitintegration, but I'm not 100% sure. I'll set something up to share the code

**Comment by antoine-levitt** [comment]
You should have gotten an invite. Just run test_integration_graphene.jl, removing the Pkg.activate line

**Comment by maltezfaria** [comment]
I checked, and the issue does not seem to come from `lc` being bigger than `hc`. Plotting the function I see this:

![Screenshot 2024-10-01 at 19 10 43](https://github.com/user-attachments/assets/9bd19ea8-1296-42a8-b969-ad4840bf716b)

which appears non-smooth at `(1/3,2/3)` and `(2/3,1/3)`. Is that expected?

**Comment by antoine-levitt** [comment]
Yup, that's the lower band of the dispersion relation of graphene, which has two conical intersections at the dirac points (the whole reason why graphene is interesting). I see in the code I forgot to shift bound_phi (but not phi) so something is wrong on my end, I'll fix it. (still the box probably shouldn't get mixed up)

**Comment by antoine-levitt** [comment]
Fixed the code and there is no issue now so probably it was not a problem from the package. It's now working! (and giving wrong results but that's most probably my fault). I'll debug it when I get the time. Number of evals is (with default settings and order=20) 30k phi evals, and about 1k evals each of bound, grad and bound_grad, which is not bad. I'll fix the code and make more detailed comparisons.

**Comment by maltezfaria** [comment]
Yeah, I saw that the bounds were wrong, should have said something...

Maybe it makes sense to add a `test_interface` utility function that can verify that the interface is "correct". We could e.g. test `bound` against a `extrema` over many points, test `gradient` against a finite difference, and test `bound_gradient` against finite difference + `bound`?

**Comment by maltezfaria** [comment]
And I still don't know what you mean by `HyperRectangle` getting confused 🤔

**Comment by antoine-levitt** [comment]
OK no my bad I was getting confused with the printing, I thought it has having a lc bigger than a hc. Testing the interface is not really your responsability I would say. One thing that came up during development is that it's a bit annoying to handle the conversion back and to intervals. Maybe just change the API so that bound(phi, rec) becomes phi(rec) where rec is a vector of intervals, and then the user overloads the call to phi with a vector of intervals. You can even get rid of the API altogether by having the user overload calls to phi with duals.
